### ISSUE TITLE
Store Bower components in devDependencies instead of a separate bower.json

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-mocha#28]
Currently the generator changes the working directory before installing dependencies, which screws up other generators which are running in parallel and want to do something with local files. It would be ideal if this generator could insert the test dependencies in the existing `bower.json`'s `devDependencies`, as suggested in #25. Apart from it being more convenient, it makes more sense too.

I was already fiddling around with that, but I'm not sure if it's possible to do without causing a file conflict?

**Comment by eddiemonge** [comment]
@SBoudrias can you help come up with a solution for the write conflict? Is it a matter of better composability in this?

**Comment by SBoudrias** [comment]
If both generators are using `yeoman-generator` >= 0.18, there won't be writing conflicts as long as every writes occurs before the initial conflict phase.
